### ISSUE TITLE
Latest Android studio/NDK toolchain sets CMAKE_SYSTEM_PROCESSOR to "armv7"

### ISSUE THREAD

**Issue by psiha** [pytorch/cpuinfo#11]
...not "armv7-a" as the cpuinfo CMake files expect...

**Comment by Maratyszcza** [comment]
Which one? Just checked Android NDK r18, it does `set(CMAKE_SYSTEM_PROCESSOR armv7-a)`

**Comment by psiha** [comment]
You are right, I'm sorry - it was my own CMake code that clobbered it...
