### ISSUE TITLE
CPUInfo reporting incorrect core count for Apple A10 (iPhone 7/7+)

### ISSUE THREAD

**Issue by Diarrhio** [pytorch/cpuinfo#12]
According to https://en.wikipedia.org/wiki/Apple_A10 (and other sites documenting it), the Apple A10 processor has 4 cores, with two big and two LITTLE cores.

However CPUInfo is reporting only 2 cores (1 cluster with 2 cores, to be exact). There is also some log information being emitted:

```
Error in cpuinfo: sysctlbyname("hw.packages") failed: Operation not permitted
Error in cpuinfo: sysctlbyname("hw.cacheconfig") failed: Operation not permitted
Error in cpuinfo: sysctl("HW_L3CACHESIZE") failed: Invalid argument
```

This is with the latest revision of CPUInfo.

**Comment by Maratyszcza** [comment]
Even though Apple A10 has 2+2 cores, exposes only two cores at a time. In such situations (both on iOS and Android) cpuinfo shows only high-performance cores, because if an app is doing compute-intensive work, the scheduler will move it to high-performance cores.
