### ISSUE TITLE
Crash on Windows ARM64

### ISSUE THREAD

**Issue by MoeMod** [pytorch/cpuinfo#123]
![image](https://user-images.githubusercontent.com/37328384/202224427-3cb49b19-d6a0-4919-928f-0cc695c640e9.png)
tested with Windows Dev Kit 2023 (8cx) on Windows 11 ARM
maybe it got unexpected group_id.

**Comment by Maratyszcza** [comment]
I believe this was fixed in bc7c739f80abeb6e58898417e280d532c1fe7ba6
