### ISSUE TITLE
exynos9810 problem

### ISSUE THREAD

**Issue by Timen** [pytorch/cpuinfo#193]
I'm unsure this has already been integrated but for certain Exynos 9810 devices on a specific android version it will report to support certain instructions but only some of the cores actually do as discussed in this LLVM post https://reviews.llvm.org/D114523

> Big.LITTLE Heterogeneous architectures, as described by ARM [1],
> require that the instruction set architecture of the big and little
> cores be compatible. However, the Samsung Exynos 9810 is known to
> have different ISAs in its core.
> According to [2], some cores are ARMv8.2 and others are ARMv8.0.
> 
> Since LSE is for ARMv8.1 and later, it should be disabled
> for this broken CPU.

**Comment by Maratyszcza** [comment]
I think you're referring to [this snippet](https://github.com/pytorch/cpuinfo/blob/main/src/arm/linux/aarch64-isa.c#L47-L49)

**Comment by Timen** [comment]
Ah yes, exactly! Sorry I wasn't able to find it, and figure doesn't hurt to double check 👍
