### ISSUE TITLE
There is a bug. The order is reversed.

### ISSUE THREAD

**Issue by pengcuo** [pytorch/cpuinfo#23]
sdm660_64:/data/pengcuo # cat /proc/cpuinfo                                                                                                                 
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 2

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 2

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 2

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 2

sdm660_64:/data/pengcuo # ./cpu-info                                                                                                                        
SoC name: Qualcomm Snapdragon 660
Cores:
	0: 1 processor (0), ARM Cortex-A73
	1: 1 processor (1), ARM Cortex-A73
	2: 1 processor (2), ARM Cortex-A73
	3: 1 processor (3), ARM Cortex-A73
	4: 1 processor (4), ARM Cortex-A53
	5: 1 processor (5), ARM Cortex-A53
	6: 1 processor (6), ARM Cortex-A53
	7: 1 processor (7), ARM Cortex-A53
Logical processors:
	0
	1
	2
	3
	4
	5
	6
	7

**Comment by Maratyszcza** [comment]
This is a feature, not a bug: cpuinfo sorts clusters of processors by decreasing performance, i.e. cluster 0 will be the big cluster, cluster 1 - the middle cluster, cluster 2 - the little cluster. Processors within a cluster are not sorted. If you want to use the system processor id on Linux, you can get it from `cpuinfo_processor.linux_id`.
