### ISSUE TITLE
Request a release

### ISSUE THREAD

**Issue by weijianwen** [pytorch/cpuinfo#3]
Hi, is it possible to publish release versions regularly? Rather than a git hash 'abcdxxxxxxxxxxxx', a relase version like '0.1' will benefit for tests and integration, making it easier to reproduce results against a specific version.

**Comment by Maratyszcza** [comment]
I prefer not to have release versions, for reasons outlined in Maratyszcza/FP16#3. Please use the latest master version, or a specific hash.
