### ISSUE TITLE
[cmake/feature request] add USE_SYSTEM_GTEST flag

### ISSUE THREAD

**Issue by cdluminate** [pytorch/cpuinfo#5]
which is a distribution friendly feature.

**Comment by Maratyszcza** [comment]
@cdluminate Sounds reasonable. Could you create a PR?

**Comment by Maratyszcza** [comment]
Another option is to configure without unit tests for a distro package, e.g. `-D CPUINFO_BUILD_UNIT_TESTS=OFF -D CPUINFO_BUILD_MOCK_TESTS=OFF -D CPUINFO_BUILD_BENCHMARKS=OFF`

**Comment by cdluminate** [comment]
We'd better not disable the tests. I'll take a look at adding this flag.

**Comment by cdluminate** [comment]
Anyone who wants to build cpuinfo with system provided googletest could define the `GOOGLETEST_SOURCE_DIR` cmake variable as e.g. `/usr/src/googletest/`.

**Comment by adamjstewart** [comment]
Would love to see this feature so I don't have to compile googletest/benchmark from source just to run the tests even though I already have both of them installed.
