### ISSUE TITLE
Instructions for building for iOS?

### ISSUE THREAD

**Issue by Diarrhio** [pytorch/cpuinfo#6]
Trying to configure/build for iOS using some of the various iOS CMake toolchain files out there, but just running into a bunch of problems or toolchains that require me to modify this project's CMakeLists.txt file. Would you mind sharing your toolchain or sharing instructions on how to build?

**Comment by Maratyszcza** [comment]
You may try this toolchain file for CMake: https://github.com/Yangqing/ios-cmake/tree/8abaed637d56f1337d6e1d2c4026e25c1eade724. PyTorch 1.0 builds on iOS use it, and they include cpuinfo as part of the build.

**Comment by Diarrhio** [comment]
Hmmm. I tried a different ios toolchain file, similar to that one, and got the OS builds working, but couldn't get the simulator builds working (I'm trying to build both to generate a fat cpuinfo.a file with all ios and iossimulator slices in there).  The simulator configuration is still including ARM sources and I'm still trying to figure out which of the other sources they are supposed to include instead... x86 or mach (my knowledge of cpu architectures and platforms is somewhat limited).

When trying tool toolchain you linked to above, I get a cmake configure failure:
`# CMake invocation
cmake ../cpuinfo-master-67705b25ddeb6ef -GXcode -DCMAKE_TOOLCHAIN_FILE=~/Downloads/iOS.cmake -DIOS_PLATFORM=OS -DCPUINFO_BUILD_BENCHMARKS=FALSE -DCPUINFO_BUILD_MOCK_TESTS=FALSE -DCPUINFO_BUILD_TOOLS=FALSE -DCPUINFO_BUILD_UNIT_TESTS=FALSE -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=9.0
`

`CMake output
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/dario/Downloads/cpuinfo-master-67705b25ddeb6ef-out-os/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_8f2fe" "-configuration" "Debug"
    === BUILD TARGET cmTC_8f2fe OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform
    warning: iOS 11.4.0 does not support armv7
    warning: iOS 11.4.0 does not support armv7s
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/dario/Downloads/cpuinfo-master-67705b25ddeb6ef-out-os/CMakeFiles/CMakeOutput.log".
See also "/Users/dario/Downloads/cpuinfo-master-67705b25ddeb6ef-out-os/CMakeFiles/CMakeError.log".
`

**Comment by Diarrhio** [comment]
OK, so I was ultimately able to get this to work, but not using the toolchain file you referenced above. I used the iOS toolchain found [here](https://github.com/servo/libfreetype2/blob/master/freetype2/builds/cmake/iOS.cmake). I had to change one line
`set(IOS_ARCH i386)`
to 
`set(IOS_ARCH "i386 x86_64")`
to include both simulator arches.

The command line I'm using for device builds is:
`cmake ../cpuinfo-master-67705b25ddeb6ef -GXcode -DCMAKE_TOOLCHAIN_FILE=iOS.cmake -DIOS_PLATFORM=OS -DCPUINFO_BUILD_BENCHMARKS=FALSE -DCPUINFO_BUILD_MOCK_TESTS=FALSE -DCPUINFO_BUILD_TOOLS=FALSE -DCPUINFO_BUILD_UNIT_TESTS=FALSE -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=9.0`

and for simulator builds is:
`cmake ../cpuinfo-master-67705b25ddeb6ef -GXcode -DCMAKE_TOOLCHAIN_FILE=iOS.cmake -DIOS_PLATFORM=SIMULATOR -DCPUINFO_BUILD_BENCHMARKS=FALSE -DCPUINFO_BUILD_MOCK_TESTS=FALSE -DCPUINFO_BUILD_TOOLS=FALSE -DCPUINFO_BUILD_UNIT_TESTS=FALSE -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=9.0 -DCMAKE_SYSTEM_PROCESSOR=x86_64`
