### ISSUE TITLE
undefined reference to `cpuinfo_loongarch_linux_init'

### ISSUE THREAD

**Issue by manhongnie** [pytorch/cpuinfo#63]
My pytorch version is 1.8
My computer is a loongarch, I want to adapt the cpuinfo library to my computer, so I added cpu_loongarch_linux_init according to the function cpuinfo_arm_linux_init, all the definitions are the same, why still report an error, the following is a hint
""/Usr/bin/ld: ../lib/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
(.text+0x4): undefined reference to `cpuinfo_loongarch_linux_init'
/usr/bin/ld: (.text+0x8): undefined reference to `cpuinfo_loongarch_linux_init'
/usr/bin/ld: (.text+0x8): undefined reference to `cpuinfo_loongarch_linux_init'
/usr/bin/ld: ../lib/libtorch_cpu.so: hidden symbol `cpuinfo_loongarch_linux_init' isn't defined"

**Comment by nmanhong** [comment]
1

**Comment by Maratyszcza** [comment]
The question is about generic C development and outside of the scope of this project.
