### ISSUE TITLE
Frequency support

### ISSUE THREAD

**Issue by Diarrhio** [pytorch/cpuinfo#7]
Any ETA on when you plan to expose frequency information, if ever?

**Comment by Maratyszcza** [comment]
There are plans to expose frequency, but not ETA on when it will happen

**Comment by Diarrhio** [comment]
In the Readme, you have the following:

```
// Get the size of level 1 data cache on the fastest core in the processor (e.g. big core in big.LITTLE ARM systems):
const size_t l1_size = cpuinfo_get_processor(0)->cache.l1d->size;
```

Does that mean it's safe to assume that the first cluster will always be the faster cluster on big.LITTLE ARM systems? Basically, trying to get to the faster cores/processors w/o having frequency information.

Thanks!

**Comment by Maratyszcza** [comment]
@Diarrhio Yes, clusters are sorted by microarchitecture, then by frequency (if available). The first cluster is the most performance cluster.
