### ISSUE TITLE
Detect/report big.LITTLE w/o GTS

### ISSUE THREAD

**Issue by psiha** [pytorch/cpuinfo#9]
Early big.LITTLE implementations (e.g. Exynos 5410, Apple A10) did not support running both clusters at the same time - please add the ability to distinguish between these cases (as it makes a difference for example for effective CPU cache sizes detection if a task can be scheduled to run on both the smaller and larger CPUs)...

**Comment by Maratyszcza** [comment]
Similar to #12

**Comment by psiha** [comment]
This is not similar to #12 - I was asking that cpuinfo explicitly provide the information whether or not all the clusters can operate simultaneously - so for A10 it should not report one cluster but both and additionally report that only one can be active at any given time...
