### ISSUE TITLE
IOS A12 neon dot error

### ISSUE THREAD

**Issue by chenqy4933** [pytorch/cpuinfo#94]
I use cpuinfo in ios, and detect the arm neon dot instruction, and get the result:

ios-gtest: Begin to check cpu information, !!!!!!!!!!!!!!!!!!!!!!!!!!!
ios-gtest: cpuinfo_get_package(0)->name: Apple A12
ios-gtest: cpu processor count is : 6
ios-gtest: cpu support neon: 1
ios-gtest: cpu support fp16: 1
ios-gtest: cpu support dot: 0

It seems the A12 processor is not support neon dot instruction? but A12 arch is above than armv8.2, I don't know the reason, maybe there is a bug?

**Comment by Maratyszcza** [comment]
NEON-DOT is optional in ARMv8.2, required in ARMv8.4. Apple SoCs before A13 doesn't support dot production instructions.

**Comment by chenqy4933** [comment]
> NEON-DOT is optional in ARMv8.2, required in ARMv8.4. Apple SoCs before A13 doesn't support dot production instructions.

yes，yes，the most android arm processor supported dot mislead me。

thanks！
